In [1]:
import shelve

time = 4

# f = shelve.open("washedPoints-Closer-Multi3-%d.dat"%(time-1))

f =shelve.open("washedPoints-E-Multi6-3.dat")

print f.keys()

['Bound_Points', 'Inner_Points']


In [2]:
from pprint import pprint
import handytools as hd

bound_Points = hd.mylst(f["Bound_Points"])
pprint(bound_Points[:20:2])

[array([ 58.        ,  -5.8222661 ,   3.55852365], dtype=float32),
 array([ 56.        ,  -8.65282917,   3.18984604], dtype=float32),
 array([ 54.        , -10.98993778,   3.03272605], dtype=float32),
 array([ 52.        , -13.02089691,   2.97639298], dtype=float32),
 array([ 50.        , -14.80576801,   3.02884507], dtype=float32),
 array([ 48.        , -16.36594582,   3.1370995 ], dtype=float32),
 array([ 46.        , -17.68042946,   3.29279089], dtype=float32),
 array([ 44.        , -18.64616203,   3.45144844], dtype=float32),
 array([ 42.        , -19.01983452,   3.53607321], dtype=float32),
 array([ 40.        , -18.71062469,   3.5251255 ], dtype=float32)]


In [3]:
from operator import itemgetter
import numpy as np

avg =  sum(bound_Points.getz()) / len(bound_Points)
stderr = np.std(bound_Points.getz(),)
print "The average is: %.3f, the std error is :%.3f"%(avg, stderr)

alpha_1 = 0.5
alpha_2 = 1.0

new_points = hd.mylst([(0.0, 0.0), (60.0, 0.0)])

def adjustPoint(x_val, y_val, z_val, z_avg, alpha_low=0.5, alpha_high=1.0):
    if z_val < z_avg:
        y_adjusted = y_val + alpha_low*(z_val - z_avg)
        point = (x_val, max(0.6, y_adjusted))
    else:
        y_adjusted = y_val + alpha_high*(z_val - z_avg)
        point = (x_val, max(0.6, y_adjusted))
    return point

for x, y, z in bound_Points:
    # 利用 y > 0 把原来的端点也过滤掉
    if x > 0 and y > 0:
        point = adjustPoint(x, y, z, avg, alpha_low=0.5, alpha_high=0.5)
#         if abs(point[0] - 1.0) < 0.001 and point[1] < 1.05:
#             point = (1.0, 1.4)
        new_points.append(point)

new_points = hd.mylst(sorted(new_points, key=itemgetter(0),))

pprint(new_points)

The average is: 3.259, the std error is :0.296
[(0.0, 0.0),
 (0.23155425, 1.1898972432987363),
 (0.50714457, 2.2480741184131769),
 (0.82465142, 3.2653049867527155),
 (1.0, 3.7960422675983576),
 (1.2105888, 4.2387464683429865),
 (1.6743459, 5.1886512678043513),
 (2.0, 5.8247764747516779),
 (2.2023606, 6.1245712678806452),
 (2.8221343, 7.0666217248813776),
 (3.0, 7.333305184163299),
 (3.5190878, 8.0171530883686213),
 (4.0, 8.6430787485019831),
 (4.2875834, 8.9728164117710261),
 (5.0, 9.7783642452137141),
 (5.1601295, 9.9421986978428034),
 (6.0, 10.783690397061553),
 (6.1513143, 10.924718682088104),
 (7.0, 11.68104607275888),
 (7.2886939, 11.922219697751251),
 (8.0, 12.486302081860748),
 (8.6008615, 12.934577647961822),
 (9.0, 13.214157883443084),
 (10.0, 13.868083898343292),
 (10.15394, 13.985488836087432),
 (11.0, 14.441877905644622),
 (12.0, 14.92726201228067),
 (12.303864, 15.082314078129974),
 (13.0, 15.301191512860504),
 (14.0, 15.527883593358245),
 (15.0, 15.610649530209747),
 (16.

In [4]:
import matplotlib.pyplot as plt

plt.figure()
plt.scatter(new_points.getx(),new_points.gety())
plt.show()

In [5]:
result = hd.coord_generator(new_points,interval=1.0, start=0.0, end=60.0)
print 'the keys of output is:\n\t',result.keys()

The interpolation points sorted by x:
	[(0.0, 0.0), (0.23155425, 1.1898972432987363), (0.50714457, 2.2480741184131769), (0.82465142, 3.2653049867527155), (1.0, 3.7960422675983576), (1.2105888, 4.2387464683429865), (1.6743459, 5.1886512678043513), (2.0, 5.8247764747516779), (2.2023606, 6.1245712678806452), (2.8221343, 7.0666217248813776), (3.0, 7.333305184163299), (3.5190878, 8.0171530883686213), (4.0, 8.6430787485019831), (4.2875834, 8.9728164117710261), (5.0, 9.7783642452137141), (5.1601295, 9.9421986978428034), (6.0, 10.783690397061553), (6.1513143, 10.924718682088104), (7.0, 11.68104607275888), (7.2886939, 11.922219697751251), (8.0, 12.486302081860748), (8.6008615, 12.934577647961822), (9.0, 13.214157883443084), (10.0, 13.868083898343292), (10.15394, 13.985488836087432), (11.0, 14.441877905644622), (12.0, 14.92726201228067), (12.303864, 15.082314078129974), (13.0, 15.301191512860504), (14.0, 15.527883593358245), (15.0, 15.610649530209747), (16.0, 15.553379480160919), (17.0, 15.36811

In [6]:
hd.result_visualize(result)
hd.abaqusInputDataGenerator_shelveVersion(outPath="modelPoints-Current.dat", time=time, **result)

shelveVersion Complete!


In [7]:
# a = max(-0.66,0.1)

# print a

In [8]:
[x for x in np.arange(0,5.2,0.1) if x % 1.0 == 0]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0]